CREATE TABLE supplier(
SNO TEXT PRIMARY KEY,
SNAME TEXT,
STATUS INTEGER,
CITY TEXT
);
INSERT INTO supplier(SNO,SNAME,STATUS,CITY) VALUES ('S1','SMITH',20,'LONDON'),
('S2','JAMES',20,'PARIS'),
('S3','LUCAS',40,'PARIS'),
('S4','SMTH',20,'LONDON'),
('S5','STH',30,'ATHENS');
SELECT*FROM supplier;
SELECT SNAME,CITY FROM supplier;
SELECT * FROM supplier WHERE STATUS=20;
SELECT * FROM supplier WHERE CITY="PARIS";
INSERT INTO supplier(SNO,SNAME,CITY) VALUES("101","PRATHAM","DELHI");
SELECT * FROM supplier;