CREATE TABLE IF NOT EXISTS STUDENT (
ROLL_NO TEST PRIMARY KEY,
NAME TEXT NOT NULL,
ADDRESS TEXT,
PHONE TEXT,
AGE INTEGER
);
INSERT INTO STUDENT(ROLL_NO ,
NAME ,
ADDRESS ,
PHONE ,
AGE) VALUES
('1','MAM','MUMBAI','********',28),
('2','SAM','PARIS','********',27),
('3','RAM','TOKYO','********',20),
('4','RA','HEYDRABAD','********',38),
('5','RM','DELHI','********',28),
('6','AM','DELHI','********',20);
SELECT*FROM STUDENT;
SELECT*FROM STUDENT WHERE AGE = 18 AND ADDRESS='DELHI';
SELECT*FROM STUDENT WHERE AGE = 18 AND NAME='RAM';
SELECT*FROM STUDENT WHERE NAME = 'RAM' OR NAME='SAM';
SELECT*FROM STUDENT WHERE NAME = 'RAM' OR AGE=20;
SELECT*FROM STUDENT WHERE AGE = '28' AND (NAME='SAM' OR NAME = 'RAM');