CREATE TABLE IF NOT EXISTS NOBEL_WIN(
YEAR INTEGER,
SUBJECT TEXT,
WINNER TEXT,
COUNTRY TEXT,
CATEGORY TEXT
);
INSERT INTO NOBEL_WIN(
YEAR ,
SUBJECT ,
WINNER ,
COUNTRY ,
CATEGORY)VALUES
(1970,'PHYSICS','UNG','USA','SCIENTIST'),
(1971,'PHYSICS','TNG','RUSSIA','SCIENTIST'),
(1975,'PHYSIOLOGY','TUG','GERMANY','SCIENTIST'),
(1977,'CHEMISTRY','TUN','FRANCE','LINGUIST'),
(1980,'PHYSICS','G','SWEEDEN','SCIENTIST'),
(1982,'ECCONOMICS','FUNG','SWEEDEN','SCIENTIST'),
(1977,'BIOLOGY','TUNO','SWEEDEN','SCIENTIST'),
(1975,'PHYSICS','TUNQ','SWEEDEN','SCIENTIST'),
(1934,'LITERATURE','RUNG','SWEEDEN','SCIENTIST'),
(1936,'PHYSICS','TUNE','SWEEDEN','SCIENTIST');
SELECT *               
FROM NOBEL_WIN
WHERE SUBJECT NOT LIKE 'P%';