CREATE TABLE IF NOT EXISTS PRODUCTS(
PRODUCT_ID TEXT,
PRODUCT_NAME TEXT,
SUPPLIER_ID TEXT,
CATEGORY_ID TEXT,
UNIT_TEXT,
PRICE_REAL
);
INSERT INTO PRODUCTS(PRODUCT_ID,
PRODUCT_NAME,
SUPPLIER_ID,
CATEGORY_ID,
UNIT_TEXT,
PRICE_REAL
)VALUES
('1','TOM','1','1','10 BOXES*20 BAGS',18),
('2','TAM','1','1','24-12 OZ BOTTLES',19),
('3','TO','1','2','12-550 ML BOTTLES',10),
('4','OM','2','2','48-6 OZ JARS',22),
('5','TM','2','2','36 BOXES',28);
SELECT COUNT(PRODUCT_ID) AS Product_Count
FROM PRODUCTS;
SELECT AVG(PRICE_REAL) AS Average_Price
FROM PRODUCTS;
SELECT SUM(PRICE_REAL) AS Total_Price
FROM PRODUCTS;