import scipy.stats as stats 
prob1=stats.poisson.pmf(6,10)
print("probability of raining in 6 days ",prob1)
prob2=stats.poisson.pmf(12,10)
print("probability of raining in 12 days ",prob2)
prob3=stats.poisson.pmf(13,10)
print("probability of raining in  13 days ",prob3)
prob4=stats.poisson.pmf(14,10)
print("probability of raining in  14 days ",prob4)
prob5=stats.poisson.pmf(15,10)
print("probability of raining in  15 days ",prob5)
prob6=stats.poisson.pmf(16,10)
print("probability of raining in  16 days ",prob6)
prob7=stats.poisson.pmf(17,10)
print("probability of raining in  17 days ",prob7)
prob8=stats.poisson.pmf(18,10)
print("probability of raining in  18 days ",prob8)